package dev.lightdream.chunkgangs.config;

import dev.lightdream.chunkgangs.core.BConfig;
import org.bukkit.ChatColor;

public enum Lang {
    PREFIX("&bGangs > &7"),
    LANG_CONSOLE("Console"),
    LANG_ENABLED("enabled"),
    LANG_DISABLED("disabled"),
    TIME_NOW("now"),
    TIME_YEARS_SINGULAR("year"),
    TIME_YEARS_PLURAL("years"),
    TIME_MONTHS_SINGULAR("month"),
    TIME_MONTHS_PLURAL("months"),
    TIME_WEEKS_SINGULAR("week"),
    TIME_WEEKS_PLURAL("weeks"),
    TIME_DAYS_SINGULAR("day"),
    TIME_DAYS_PLURAL("days"),
    TIME_HOURS_SINGULAR("hour"),
    TIME_HOURS_PLURAL("hours"),
    TIME_MINUTES_SINGULAR("minute"),
    TIME_MINUTES_PLURAL("minutes"),
    TIME_SECONDS_SINGULAR("second"),
    TIME_SECONDS_PLURAL("seconds"),
    MSG_ERROR("Error occured, please contact server owner."),
    MSG_NOACCESS("You don't have access to this command."),
    MSG_PLAYERONLY("This command can be used only in the game."),
    MSG_INGANGONLY("You have to be in a gang to use this command."),
    MSG_NOGANGONLY("You can't use this command while in a gang."),
    MSG_TOOLOWRANK("You have to be at least %rank% to do this."),
    MSG_USAGE_FIGHT("Invalid command usage. Please check /gang help"),
    MSG_USAGE_GANG("Invalid command usage. Please check /gang help"),
    MSG_USAGE_GANGADMIN("Invalid command usage. Correct usage: /gadmin <arena|bank|disband|reload|spy>"),
    MSG_USAGE_SUBCOMMAND("Invalid command usage. Correct usage: %usage%"),
    MSG_MODULE_DISABLED("This module has been disabled by the server owner."),
    MSG_GANGS_DISABLED("Gangs have been disabled in this world."),
    MSG_INVALIDGANG("Invalid gang name specified."),
    MSG_INVALIDPLAYER("Invalid player name specified."),
    MSG_INVALIDAMOUNT("Invalid money amount specified."),
    MSG_TELEPORT_TELEPORT("You will be teleported in %time%."),
    MSG_TELEPORT_AWAITING("You are already waiting for teleportation."),
    MSG_TELEPORT_CANCELLED("Pending teleportation request has been cancelled."),
    MSG_ALLYCHAT_TOGGLED("You have %state% ally chat."),
    MSG_FIGHTS_START_WILLSTART("Your gang will begin a fight against %gang% on arena %arena% in %time%. Required members amount: %membersamount%. Join the fight using &b/fight join&7."),
    MSG_FIGHTS_START_CANNOT_MEMBERS("There are too few players from %gang% to begin the fight, the fight has been cancelled."),
    MSG_FIGHTS_START_CANNOT_MONEY("Gang %gang% doesn't have enough money to pay the entry fee, the fight has been cancelled."),
    MSG_FIGHTS_START_STARTED_BROADCAST("The fight between %gang1% and %gang2% has begun!"),
    MSG_FIGHTS_START_STARTED_INARENA("The fight has begun!"),
    MSG_FIGHTS_START_STARTED_INGANG("Your gang has begun the fight against %gang%!"),
    MSG_FIGHTS_END_MONEY("You have won $%amount% from the fight."),
    MSG_FIGHTS_END_WON_BROADCAST("Gang %winner% has won the fight against %loser%!"),
    MSG_FIGHTS_END_WON_INGANG("Your gang has won the fight against %gang%. $%amount% have been added to gang's bank account."),
    MSG_FIGHTS_END_LOST_INGANG("Your gang has lost the fight against %gang%."),
    MSG_FIGHTS_END_TELEPORT("You will be teleported out of the arena in %time%."),
    MSG_FIGHTS_END_ENDED_BROADCAST("Fight between %gang1% and %gang2% has ended."),
    MSG_FIGHTS_CANTUSECOMMAND("You can't use that command when fighting."),
    MSG_FIGHTS_CANTMOVE("You can't move until the fight starts."),
    MSG_FIGHTS_CANTLEAVEARENA("You can't leave the fight arena."),
    MSG_FIGHTS_ELIMINATED_ELIMINATED("You have been eliminated from the fight."),
    MSG_FIGHTS_ELIMINATED_INARENA("%player% has been eliminated! %amount% players left from %gang%."),
    MSG_FIGHTS_ARENASTATE_NOTCONFIGURED("not configured"),
    MSG_FIGHTS_ARENASTATE_EMPTY("empty"),
    MSG_FIGHTS_ARENASTATE_WAITING("waiting for players"),
    MSG_FIGHTS_ARENASTATE_INPROGRESS("in progress"),
    MSG_FIGHTS_ARENASTATE_ENDED("restarting"),
    MSG_FIGHT_ACCEPT_OWN("You can't fight your own gang."),
    MSG_FIGHT_ACCEPT_ALLY("You can't fight an allied gang."),
    MSG_FIGHT_ACCEPT_NOTCHALLENGED("%gang% hasn't challenged you to fight."),
    MSG_FIGHT_ACCEPT_ALREADYFIGHTING_OWN("Your gang is already fighting."),
    MSG_FIGHT_ACCEPT_ALREADYFIGHTING_ENEMY("%gang% is already fighting."),
    MSG_FIGHT_ACCEPT_NOEMPTYARENA("There are no available arenas to begin the fight, please try again later."),
    MSG_FIGHT_ACCEPT_NOTENOUGHMEMBERS_OWN("There aren't enough online players from your gang to start the fight."),
    MSG_FIGHT_ACCEPT_NOTENOUGHMEMBERS_ENEMY("There aren't enough online players from %gang% to start the fight."),
    MSG_FIGHT_ACCEPT_NOTENOUGHMONEY_OWN("Your gang needs $%amount% on bank account to start the fight."),
    MSG_FIGHT_ACCEPT_NOTENOUGHMONEY_ENEMY("%gang% doesn't have enough money to start the fight."),
    MSG_FIGHT_ACCEPT_NOTENOUGHPRIVATEMONEY("You don't have enough money."),
    MSG_FIGHT_ACCEPT_PAIDPRIVATEMONEY("You have paid $%amount% deposit for the fight."),
    MSG_FIGHT_CHALLENGE_OWN("You can't challenge your own gang."),
    MSG_FIGHT_CHALLENGE_ALLY("You can't challenge an allied gang."),
    MSG_FIGHT_CHALLENGE_ALREADYCHALLENGED_OWN("Your gang has already challenged %gang%."),
    MSG_FIGHT_CHALLENGE_ALREADYCHALLENGED_ENEMY("Your gang has been already challenged by %gang%. You can accept using &b/fight accept %gang%&7."),
    MSG_FIGHT_CHALLENGE_INVALID_MEMBERS("Invalid members amount specified."),
    MSG_FIGHT_CHALLENGE_MEMBERS_RANGE("Please specify members amount between %min% and %max%."),
    MSG_FIGHT_CHALLENGE_MONEY_RANGE("Please specify money amount between %min% and %max%."),
    MSG_FIGHT_CHALLENGE_NOTENOUGHMEMBERS("There aren't enough online players from your gang."),
    MSG_FIGHT_CHALLENGE_NOTENOUGHMONEY("Your gang doesn't have that much money."),
    MSG_FIGHT_CHALLENGE_NOTENOUGHPRIVATEMONEY("You don't have enough money."),
    MSG_FIGHT_CHALLENGE_PAIDPRIVATEMONEY("You have paid $%amount% deposit for the challenge."),
    MSG_FIGHT_CHALLENGE_CHALLENGED_BY("Your gang has been challenged by %gang% to fight! Required members: %membersamount%, entry fee: $%amount%. You can accept using &b/fight accept %gang%&7."),
    MSG_FIGHT_CHALLENGE_CHALLENGED_INGANG("Your gang has challenged %gang% to fight! Required members: %membersamount%, entry fee: $%amount%."),
    MSG_FIGHT_CHALLENGE_CHALLENGED_CHALLENGED("You have challenged %gang% to fight."),
    MSG_FIGHT_DECLINE_NOTCHALLENGED("%gang% hasn't challenged you to fight."),
    MSG_FIGHT_DECLINE_DECLINED("You've declined to fight %gang%."),
    MSG_FIGHT_JOIN_NOTFIGHTING("Your gang isn't fighting at this moment."),
    MSG_FIGHT_JOIN_CANNOTJOIN("You can join only fights which haven't started yet."),
    MSG_FIGHT_JOIN_JOINED("%player% (%gang%) has joined the fight (players from %gang%: %membersamount%)."),
    MSG_FIGHT_LEAVE_NOTFIGHTING("Your gang isn't fighting at this moment."),
    MSG_FIGHT_LEAVE_NOTINARENA("You aren't inside any fight arena."),
    MSG_FIGHT_LEAVE_LEFT("%player% (%gang%) has left the fight arena."),
    MSG_GANG_ALLY_OWN("You can't send ally request to your own gang."),
    MSG_GANG_ENEMY_OWN("You can't be enemy to your own gang."),
    MSG_GANG_ALLY_ALREADYALLY("This gang is already your ally."),
    MSG_GANG_ENEMY_ALREADYENEMY("This gang is already your ally."),
    MSG_GANG_ALLY_REQUESTED_BY("%gang% requested for an alliance. You can accept it with /gang ally %gang%"),
    MSG_GANG_ENEMY("You are now enemy with %gang%"),
    MSG_GANG_ALREADY_ENEMY("You are already enemy with %gang%"),
    MSG_GANG_ENEMY_LIMIT("You already have the maximum number of enemy gangs"),
    MSG_GANG_ALLY_REQUESTED_INGANG("Your gang sent an alliance request to %gang%."),
    MSG_GANG_ALLY_REQUESTED_REQUESTED("Alliance request sent to %gang%."),
    MSG_GANG_ALLY_ACCEPTED_BY("Your alliance request has been accepted by %gang%."),
    MSG_GANG_ALLY_ACCEPTED_INGANG("Your gang is now in alliance with %gang%."),
    MSG_GANG_ALLY_ACCEPTED_ACCEPTED("You accepted %gang%'s alliance request."),
    MSG_GANG_CONFIRM_NONE("You don't have any actions to confirm."),
    MSG_GANG_CREATE_CANTAFFORD("You need $%amount% to create a gang."),
    MSG_GANG_CREATE_LENGTH("Specified name is either too short or too long, it may contain %min%-%max% characters."),
    MSG_GANG_CREATE_SPECIALCHARS("Specified name contains banned characters."),
    MSG_GANG_CREATE_SPACES("Gang name may not contain blank spaces."),
    MSG_GANG_CREATE_BANNEDNAME("You can't create gang with that name."),
    MSG_GANG_CREATE_ALREADYEXISTS("A gang with that name already exists."),
    MSG_GANG_CREATE_COLORS("You don't have access to use colors in the gang name."),
    MSG_GANG_CREATE_BROADCAST("Gang %gang% has been created by %player%."),
    MSG_GANG_CREATE_CREATED("You have successfully created gang %gang%."),
    MSG_GANG_DELHOME_INVALIDHOME("Invalid home specified."),
    MSG_GANG_DELHOME_DELETED("Home deleted."),
    MSG_GANG_DEMOTE_NOTINGANG("%player% isn't part of your gang."),
    MSG_GANG_DEMOTE_LOWEST("You can't demote %player% any more."),
    MSG_GANG_DEMOTE_HIGHEST("You can't demote the leader. Change the leader using /gang leader first."),
    MSG_GANG_DEMOTE_DEMOTED_BY("You have been demoted to %rank% by %player%."),
    MSG_GANG_DEMOTE_DEMOTED_INGANG("%target% has been demoted to %rank% by %player%."),
    MSG_GANG_DEMOTE_DEMOTED_DEMOTED("You have demoted %target% to %rank%."),
    MSG_GANG_DEPOSIT_INVALIDAMOUNT("Invalid amount of money specified."),
    MSG_GANG_DEPOSIT_CANTAFFORD("You don't have that much money."),
    MSG_GANG_DEPOSIT_DEPOSITED_INGANG("%player% has deposited $%amount% into gang bank account."),
    MSG_GANG_DEPOSIT_DEPOSITED_DEPOSITED("You have deposited $%amount% into gang bank account."),
    MSG_GANG_DISBAND_CONFIRM("Please the gang disband with /g confirm."),
    MSG_GANG_DISBAND_FIGHTING("You can't disband the gang during a fight."),
    MSG_GANG_DISBAND_BROADCAST("Gang %gang% has been disbanded by %player%."),
    MSG_GANG_DISBAND_DISBANDED("You have disbanded your gang."),
    MSG_GANG_FRIENDLYFIRE_DISABLED("Changing friendly fire settings has been disabled by the server owner."),
    MSG_GANG_FRIENDLYFIRE_TOGGLED_INGANG("%player% has %state% friendly fire."),
    MSG_GANG_FRIENDLYFIRE_TOGGLED_TOGGLED("You have %state% friendly fire."),
    MSG_GANG_HELP_HELP_1("&7--------------------[ &bGangs help &7]--------------------\n&7- &b/gang list &7- list of all gangs\n&7- &b/gang top &7- gangs leaderboard\n&7- &b/gang info <gang> &7- information about specified gang\n&7- &b/gang create <name> &7- create a new gang\n&7- &b/gang disband &7- disband your gang\n&7- &b/gang join <gang> &7- join specified gang \n&7- &b/gang invite <player> &7- invite player to your gang\n&7- &b/gang uninvite <player> &7- cancel player's invitation\n&7- &b/gang kick <player> &7- kick player out of your gang\n&7- &b/gang leave &7- leave your gang\n&7- &b/gang player <player> &7- specified player's statistics\n&7- &b/gang regroup <home name>  &7- request all players to regroup at specified home\n&7- &b/gang friendlyfire &7- toggle friendly fire in gang\n&7- &b/gang levelup &7- level up to higher gang level\n&7- &b/gang promote <player> &7- promote specified player to higher rank\n&7- &b/gang demote <player> &7- demote specified player to lower rank\n&7- &b/gang deposit <amount> &7- deposit money on your gang's bank account\n&7- &b/gang withdraw <amount> &7- withdraw money from your gang's bank account\n&7- &b/gang listhomes &7- list of all gang homes\n&7- &b/gang home <home> &7- teleport to specified gang home\n&7- &b/gang sethome <home> &7- set specified gang home's location\n&7- &b/gang delhome <home> &7- delete specified gang home\n&7- &b/gang ally <gang> &7- send alliance request to specified gang\n&7- &b/gang neutral <gang> &7- set relation with an ally to neutral\n&7- &b/gc on|off &7- toggle gang chat on/off\n&7- &b/gc <message> &7- send a single message on gang chat\n&7- &b/ac on|off  &7- toggle ally chat on/off\n&7- &b/ac<message> &7- send a single message on ally chat\n&7- &b/fight challenge <players amount> <money> <gang> &7- challenge specified gang for a fight\n&7- &b/fight accept <gang> &7- accept fight challenge from specified gang\n&7- &b/fight join &7- join the fight your gang takes part in\n&7- &b/fight leave &7- leave the fight your gang takes part in\n"),
    MSG_GANG_HELP_HELP_2("&7--------------------[ &bGangs help &7]--------------------\n&7- &b/gang list &7- list of all gangs\n&7- &b/gang top &7- gangs leaderboard\n&7- &b/gang info <gang> &7- information about specified gang\n&7- &b/gang create <name> &7- create a new gang\n&7- &b/gang disband &7- disband your gang\n&7- &b/gang join <gang> &7- join specified gang \n&7- &b/gang invite <player> &7- invite player to your gang\n&7- &b/gang uninvite <player> &7- cancel player's invitation\n&7- &b/gang kick <player> &7- kick player out of your gang\n&7- &b/gang leave &7- leave your gang\n&7- &b/gang player <player> &7- specified player's statistics\n&7- &b/gang regroup <home name>  &7- request all players to regroup at specified home\n&7- &b/gang friendlyfire &7- toggle friendly fire in gang\n&7- &b/gang levelup &7- level up to higher gang level\n&7- &b/gang promote <player> &7- promote specified player to higher rank\n&7- &b/gang demote <player> &7- demote specified player to lower rank\n&7- &b/gang deposit <amount> &7- deposit money on your gang's bank account\n&7- &b/gang withdraw <amount> &7- withdraw money from your gang's bank account\n&7- &b/gang listhomes &7- list of all gang homes\n&7- &b/gang home <home> &7- teleport to specified gang home\n&7- &b/gang sethome <home> &7- set specified gang home's location\n&7- &b/gang delhome <home> &7- delete specified gang home\n&7- &b/gang ally <gang> &7- send alliance request to specified gang\n&7- &b/gang neutral <gang> &7- set relation with an ally to neutral\n&7- &b/gc on|off &7- toggle gang chat on/off\n&7- &b/gc <message> &7- send a single message on gang chat\n&7- &b/ac on|off  &7- toggle ally chat on/off\n&7- &b/ac<message> &7- send a single message on ally chat\n&7- &b/fight challenge <players amount> <money> <gang> &7- challenge specified gang for a fight\n&7- &b/fight accept <gang> &7- accept fight challenge from specified gang\n&7- &b/fight join &7- join the fight your gang takes part in\n&7- &b/fight leave &7- leave the fight your gang takes part in\n"),
    MSG_GANG_HELP_HELP_3("&7--------------------[ &bGangs help &7]--------------------\n&7- &b/gang list &7- list of all gangs\n&7- &b/gang top &7- gangs leaderboard\n&7- &b/gang info <gang> &7- information about specified gang\n&7- &b/gang create <name> &7- create a new gang\n&7- &b/gang disband &7- disband your gang\n&7- &b/gang join <gang> &7- join specified gang \n&7- &b/gang invite <player> &7- invite player to your gang\n&7- &b/gang uninvite <player> &7- cancel player's invitation\n&7- &b/gang kick <player> &7- kick player out of your gang\n&7- &b/gang leave &7- leave your gang\n&7- &b/gang player <player> &7- specified player's statistics\n&7- &b/gang regroup <home name>  &7- request all players to regroup at specified home\n&7- &b/gang friendlyfire &7- toggle friendly fire in gang\n&7- &b/gang levelup &7- level up to higher gang level\n&7- &b/gang promote <player> &7- promote specified player to higher rank\n&7- &b/gang demote <player> &7- demote specified player to lower rank\n&7- &b/gang deposit <amount> &7- deposit money on your gang's bank account\n&7- &b/gang withdraw <amount> &7- withdraw money from your gang's bank account\n&7- &b/gang listhomes &7- list of all gang homes\n&7- &b/gang home <home> &7- teleport to specified gang home\n&7- &b/gang sethome <home> &7- set specified gang home's location\n&7- &b/gang delhome <home> &7- delete specified gang home\n&7- &b/gang ally <gang> &7- send alliance request to specified gang\n&7- &b/gang neutral <gang> &7- set relation with an ally to neutral\n&7- &b/gc on|off &7- toggle gang chat on/off\n&7- &b/gc <message> &7- send a single message on gang chat\n&7- &b/ac on|off  &7- toggle ally chat on/off\n&7- &b/ac<message> &7- send a single message on ally chat\n&7- &b/fight challenge <players amount> <money> <gang> &7- challenge specified gang for a fight\n&7- &b/fight accept <gang> &7- accept fight challenge from specified gang\n&7- &b/fight join &7- join the fight your gang takes part in\n&7- &b/fight leave &7- leave the fight your gang takes part in\n"),
    MSG_GANG_HELP_HELP_4("&7--------------------[ &bGangs help &7]--------------------\n&7- &b/gang list &7- list of all gangs\n&7- &b/gang top &7- gangs leaderboard\n&7- &b/gang info <gang> &7- information about specified gang\n&7- &b/gang create <name> &7- create a new gang\n&7- &b/gang disband &7- disband your gang\n&7- &b/gang join <gang> &7- join specified gang \n&7- &b/gang invite <player> &7- invite player to your gang\n&7- &b/gang uninvite <player> &7- cancel player's invitation\n&7- &b/gang kick <player> &7- kick player out of your gang\n&7- &b/gang leave &7- leave your gang\n&7- &b/gang player <player> &7- specified player's statistics\n&7- &b/gang regroup <home name>  &7- request all players to regroup at specified home\n&7- &b/gang friendlyfire &7- toggle friendly fire in gang\n&7- &b/gang levelup &7- level up to higher gang level\n&7- &b/gang promote <player> &7- promote specified player to higher rank\n&7- &b/gang demote <player> &7- demote specified player to lower rank\n&7- &b/gang deposit <amount> &7- deposit money on your gang's bank account\n&7- &b/gang withdraw <amount> &7- withdraw money from your gang's bank account\n&7- &b/gang listhomes &7- list of all gang homes\n&7- &b/gang home <home> &7- teleport to specified gang home\n&7- &b/gang sethome <home> &7- set specified gang home's location\n&7- &b/gang delhome <home> &7- delete specified gang home\n&7- &b/gang ally <gang> &7- send alliance request to specified gang\n&7- &b/gang neutral <gang> &7- set relation with an ally to neutral\n&7- &b/gc on|off &7- toggle gang chat on/off\n&7- &b/gc <message> &7- send a single message on gang chat\n&7- &b/ac on|off  &7- toggle ally chat on/off\n&7- &b/ac<message> &7- send a single message on ally chat\n&7- &b/fight challenge <players amount> <money> <gang> &7- challenge specified gang for a fight\n&7- &b/fight accept <gang> &7- accept fight challenge from specified gang\n&7- &b/fight join &7- join the fight your gang takes part in\n&7- &b/fight leave &7- leave the fight your gang takes part in\n"),
    MSG_GANG_HELP_HELP_5("&7--------------------[ &bGangs help &7]--------------------\n&7- &b/gang list &7- list of all gangs\n&7- &b/gang top &7- gangs leaderboard\n&7- &b/gang info <gang> &7- information about specified gang\n&7- &b/gang create <name> &7- create a new gang\n&7- &b/gang disband &7- disband your gang\n&7- &b/gang join <gang> &7- join specified gang \n&7- &b/gang invite <player> &7- invite player to your gang\n&7- &b/gang uninvite <player> &7- cancel player's invitation\n&7- &b/gang kick <player> &7- kick player out of your gang\n&7- &b/gang leave &7- leave your gang\n&7- &b/gang player <player> &7- specified player's statistics\n&7- &b/gang regroup <home name>  &7- request all players to regroup at specified home\n&7- &b/gang friendlyfire &7- toggle friendly fire in gang\n&7- &b/gang levelup &7- level up to higher gang level\n&7- &b/gang promote <player> &7- promote specified player to higher rank\n&7- &b/gang demote <player> &7- demote specified player to lower rank\n&7- &b/gang deposit <amount> &7- deposit money on your gang's bank account\n&7- &b/gang withdraw <amount> &7- withdraw money from your gang's bank account\n&7- &b/gang listhomes &7- list of all gang homes\n&7- &b/gang home <home> &7- teleport to specified gang home\n&7- &b/gang sethome <home> &7- set specified gang home's location\n&7- &b/gang delhome <home> &7- delete specified gang home\n&7- &b/gang ally <gang> &7- send alliance request to specified gang\n&7- &b/gang neutral <gang> &7- set relation with an ally to neutral\n&7- &b/gc on|off &7- toggle gang chat on/off\n&7- &b/gc <message> &7- send a single message on gang chat\n&7- &b/ac on|off  &7- toggle ally chat on/off\n&7- &b/ac<message> &7- send a single message on ally chat\n&7- &b/fight challenge <players amount> <money> <gang> &7- challenge specified gang for a fight\n&7- &b/fight accept <gang> &7- accept fight challenge from specified gang\n&7- &b/fight join &7- join the fight your gang takes part in\n&7- &b/fight leave &7- leave the fight your gang takes part in\n"),
    MSG_GANG_HOME_INVALIDHOME("Invalid home specified."),
    MSG_GANG_HOME_UNSAFE("Home's location is unsafe, teleportation cancelled."),
    MSG_GANG_INVITE_FULL("Your gang has reached the maximal allowed members amount (%amount% members)."),
    MSG_GANG_INVITE_ALREADYINGANG("%player% is already in a gang."),
    MSG_GANG_INVITE_ALREADYINVITED("%player% has been already invited to your gang."),
    MSG_GANG_INVITE_INVITED_BY("You have been invited to %gang% gang by %player%."),
    MSG_GANG_INVITE_INVITED_INVITED("You have invited %target% to your gang."),
    MSG_GANG_JOIN_NOTINVITED("You aren't invited to this gang."),
    MSG_GANG_JOIN_FULL("This gang is full, you can't join it."),
    MSG_GANG_JOIN_JOINED_BROADCAST("%player% has joined %gang%."),
    MSG_GANG_JOIN_JOINED_INGANG("%player% has joined your gang."),
    MSG_GANG_JOIN_JOINED_JOINED("You have joined %gang%."),
    MSG_GANG_KICK_NOTINGANG("%player% isn't part of your gang."),
    MSG_GANG_KICK_OWNSELF("You can't kick yourself. Please use /gang leave instead."),
    MSG_GANG_KICK_FIGHTING("You can't kick a player who's fighting at this moment."),
    MSG_GANG_KICK_LEADER("You can't kick the leader."),
    MSG_GANG_KICK_KICKED_BROADCAST("%target% has been kicked from %gang%."),
    MSG_GANG_KICK_KICKED_INGANG("%target% has been kicked from the gang by %player%."),
    MSG_GANG_KICK_KICKED_BY("You have been kicked from %gang% by %player%."),
    MSG_GANG_KICK_KICKED_KICKED("You kicked %target% from your gang."),
    MSG_GANG_LEADER_NOTINGANG("%player% isn't part of your gang."),
    MSG_GANG_LEADER_ALREADYLEADER("%player% is already the leader."),
    MSG_GANG_LEADER_CHANGED_BROADCAST("%player% has given the leadership of %gang% to %target%."),
    MSG_GANG_LEADER_CHANGED_INGANG("%player% has given the leadership to %target%."),
    MSG_GANG_LEADER_CHANGED_BY("You have been given the leadership of %gang% by %player%."),
    MSG_GANG_LEADER_CHANGED_CHANGED("You have given the leadership of %gang% to %target%."),
    MSG_GANG_LEAVE_LEADER("You can't leave the gang as leader, please give the leadership to someone else using /gang leader <player> first."),
    MSG_GANG_LEAVE_FIGHTING("You can't leave the gang when fighting."),
    MSG_GANG_LEAVE_NOMEMBERS("You can't leave an empty gang, please disband it instead."),
    MSG_GANG_LEAVE_LEFT_BROADCAST("%player% has left %gang%."),
    MSG_GANG_LEAVE_LEFT_INGANG("%player% has left the gang."),
    MSG_GANG_LEAVE_LEFT_LEFT("You have left %gang%."),
    MSG_GANG_LEVELUP_MAX("Your gang reached the highest available level, you can't level up any more."),
    MSG_GANG_LEVELUP_GANGCANTAFFORD("Your gang needs $%amount% on bank account to level up."),
    MSG_GANG_LEVELUP_CANTAFFORD("You need $%amount% to level up the gang."),
    MSG_GANG_LEVELUP_LEVELEDUP_BROADCAST("Gang %gang% has been upgraded to level %level%."),
    MSG_GANG_LEVELUP_LEVELEDUP_INGANG("Your gang has been upgraded to level %level%."),
    MSG_GANG_LEVELUP_LEVELEDUP_LEVELEDUP("You have upgraded your gang to level %level%."),
    MSG_GANG_LIST_NOGANGS("There are no gangs."),
    MSG_GANG_LIST_HEADER("Gangs list (%page%/%totalpages%):"),
    MSG_GANG_LIST_GANG("&7- &b%name%&7, leader: %leader%, level: %level%, members: %membersamount%"),
    MSG_GANG_LISTHOMES_NOHOMES("Gang %gang% doesn't have any homes."),
    MSG_GANG_LISTHOMES_HEADER("%gang% gang homes:"),
    MSG_GANG_NEUTRAL_OWN("You can't change relation to your own gang."),
    MSG_GANG_NEUTRAL_NOTALLY("Gang %gang% is already neutral to you."),
    MSG_GANG_NEUTRAL_NEUTRAL_INGANG("Your gang is now neutral to %gang%."),
    MSG_GANG_NEUTRAL_NEUTRAL_NEUTRAL("You have set your gang's relation to %gang% to neutral."),
    MSG_GANG_PROMOTE_NOTINGANG("%player% isn't part of your gang."),
    MSG_GANG_PROMOTE_LEADER("You can't promote %player% any more. Use /gang leader %player% in order to change the leader of the gang."),
    MSG_GANG_PROMOTE_HIGHEST("You can't promote %player% any more."),
    MSG_GANG_PROMOTE_PROMOTED_BY("You have been promoted to %rank% by %player%."),
    MSG_GANG_PROMOTE_PROMOTED_INGANG("%target% has been promoted to %rank% by %player%."),
    MSG_GANG_PROMOTE_PROMOTED_PROMOTED("You have promoted %target% to %rank%."),
    MSG_GANG_REGROUP_INVALIDHOME("Invalid home specified."),
    MSG_GANG_REGROUP_INGANG("%player% requested to regroup at home %home%."),
    MSG_GANG_SETHOME_INVALIDNAME("You can't use quotation marks in the home name."),
    MSG_GANG_SETHOME_UNSAFELOCATION("You can set home only in a safe location."),
    MSG_GANG_SETHOME_ALREADYEXISTS("Home with that name already exists."),
    MSG_GANG_SETHOME_BANNEDWORLD("You can't create home in this world."),
    MSG_GANG_SETHOME_LIMIT("Homes limit reached. Current amount: %current%, limit: %limit%"),
    MSG_GANG_SETHOME_SET("Home %home% has been set."),
    MSG_GANG_TOP_HEADER("Top %amount% gangs (sorted by %order%):"),
    MSG_GANG_TOP_GANG("%name% - Level: %level%, Kills: %kills%, deaths: %deaths%, KDR: %kdr%\n"),
    MSG_GANG_UNINVITE_NOTINVITED("%player% hasn't been invited to your gang."),
    MSG_GANG_UNINVITE_UNINVITED_BY("Your invitation to %gang% has been cancelled by %player%."),
    MSG_GANG_UNINVITE_UNINVITED_UNINVITED("You cancelled %target%'s invitation to your gang."),
    MSG_GANG_WITHDRAW_INVALIDAMOUNT("Invalid amount of money specified."),
    MSG_GANG_WITHDRAW_CANTAFFORD("There isn't enough money on gang bank account."),
    MSG_GANG_WITHDRAW_WITHDRAWN_INGANG("%player% has withdrawn $%amount% from gang bank account."),
    MSG_GANG_WITHDRAW_WITHDRAWN_WITHDRAWN("You have withdrawn $%amount% from gang bank account."),
    MSG_GANGCHAT_TOGGLED("You have %state% gang chat."),
    MSG_GANGADMIN_ARENA_INVALIDARENA("Invalid arena ID specified."),
    MSG_GANGADMIN_ARENA_INUSE("You can't edit an arena which is currently being used."),
    MSG_GANGADMIN_ARENA_LIST_NOARENAS("There are no arenas."),
    MSG_GANGADMIN_ARENA_LIST_HEADER("Arenas list:"),
    MSG_GANGADMIN_ARENA_LIST_ARENA("- ID: %id%, name: %name%, state: %state%"),
    MSG_GANGADMIN_ARENA_CREATE_ALREADYEXISTS("Arena %id% already exists."),
    MSG_GANGADMIN_ARENA_CREATE_SPECIALCHARS("Arena ID may contain only alphanumeric characters."),
    MSG_GANGADMIN_ARENA_CREATE_CREATED("Arena %id% has been created. Now set the locations using &b/gadmin arena setlocation %id% <corner1|corner2|spawn1|spawn2>&7 and save it using &b/gadmin arena save %id%&7."),
    MSG_GANGADMIN_ARENA_REMOVE_REMOVED("Arena %id% has been removed."),
    MSG_GANGADMIN_ARENA_SETLOCATION_INVALIDLOCATION("Invalid location name specified. Valid ones: corner1, corner2, spawn1, spawn2"),
    MSG_GANGADMIN_ARENA_SETLOCATION_INVALIDWORLD("You can't set the location in a different world than the other locations for this arena (%world%)."),
    MSG_GANGADMIN_ARENA_SETLOCATION_SET("Location %location% has been set for arena %id%."),
    MSG_GANGADMIN_ARENA_SETLOCATION_READYTOUSE("Arena %id% is now ready to use, save it using &b/gadmin arena save %id%&7."),
    MSG_GANGADMIN_ARENA_SETNAME_SPECIALCHARS("Arena name may contain only alphanumeric characters."),
    MSG_GANGADMIN_ARENA_SETNAME_SET("Arena's %id% name has been set to %name%. Now save it using &b/gadmin arena save %id%&7."),
    MSG_GANGADMIN_ARENA_SAVE_CANTSAVE("Arena %id% couldn't be saved. Missing locations: %locations%"),
    MSG_GANGADMIN_ARENA_SAVE_SAVED("Arena %id% has been saved."),
    MSG_GANGADMIN_BANK_BALANCE_BALANCE("%gang%'s balance: $%amount%"),
    MSG_GANGADMIN_BANK_GIVE_GIVEN("$%amount% has been added to %gang%'s bank account."),
    MSG_GANGADMIN_BANK_TAKE_TAKEN("$%amount% was taken from %gang%'s bank account."),
    MSG_GANGADMIN_BANK_TAKE_TOOMUCH("Gang %gang% doesn't have that much money."),
    MSG_GANGADMIN_BANK_RESET_RESET("%gang%'s bank account has been reset."),
    MSG_GANGADMIN_DISBAND_FIGHTING("You can't disband the gang during a fight."),
    MSG_GANGADMIN_DISBAND_DISBANDED_BROADCAST("Gang %gang% has been disbanded by %player%."),
    MSG_GANGADMIN_DISBAND_DISBANDED_DISBANDED("You have disbanded gang %gang%."),
    MSG_GANGADMIN_RELOAD_RELOADED("Configuration has been reloaded."),
    MSG_GANGADMIN_RESETGANG_RESET("%gang%'s %type% statistics were reset."),
    MSG_GANGADMIN_SPY_TOGGLED("You have %state% gang & ally chat spy for %player%."),
    MSG_GANGADMIN_SPY_TOGGLEDBY("Your gang & ally chat spy has been %state% by %player%.");

    private static BConfig config;
    private final String defaultValue;

    Lang(String var3) {
        this.defaultValue = var3;
    }

    public static void setConfig(BConfig var0) {
        config = var0;
        load();
    }

    private static void load() {
        Lang[] var0 = values();
        int var1 = var0.length;

        for (int var2 = 0; var2 < var1; ++var2) {
            Lang var3 = var0[var2];
            if (config.getConfig().getString(var3.getPath()) == null) {
                config.getConfig().set(var3.getPath(), var3.getDefaultValue());
            }
        }

        config.save();
    }

    public String getPath() {
        return this.name().replace("_", ".");
    }

    public String getDefaultValue() {
        return this.defaultValue;
    }

    public String toString() {
        return this.fixColors(config.getConfig().getString(this.getPath()));
    }

    public String toMsg() {
        boolean var1 = true;
        return var1 ? this.fixColors(config.getConfig().getString(PREFIX.getPath()) + config.getConfig().getString(this.getPath())) : this.fixColors(config.getConfig().getString(this.getPath()));
    }

    private String fixColors(String var1) {
        return var1 == null ? "" : ChatColor.translateAlternateColorCodes('&', var1);
    }
}
